theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1 : bold,italic,strikethrough,underline,|,bullist,numlist,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,styleselect,|,pastetext,pasteword,|,outdent,indent,|,undo,redo,|,image
# theme_advanced_buttons2 : formatselect,styleselect,|,pastetext,pasteword,|,outdent,indent,|,undo,redo,|,image
<<<<<<< HEAD
=======
theme_advanced_toolbar_location: "external"
>>>>>>> experiments
theme_advanced_resizing : true
skin: default
theme: advanced

style_formats:
  - title: R-to-L
    block: div
    classes: rtl
content_css : /assets/tinymce/themes/advanced/skins/default/content.css
