theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
skin: default

style_formats:
  - title: R-to-L
    block: div
    classes: rtl
content_css : /assets/tinymce/themes/advanced/skins/default/content.css
