# toolbar_location: top
# toolbar_align: left
# statusbar_location: bottom
# buttons1: "bold,italic,strikethrough,underline,|,bullist,numlist,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,styleselect,|,pastetext,pasteword,|,forecolor,backcolor,|,outdent,indent,|,undo,redo,|,link,unlink,|,code,uploadimage"
toolbar: ['bold italic strikethrough underline | bullist numlist | alignleft aligncenter alignright |  outdent indent ', 'formatselect styleselect | forecolor backcolor | link  | code uploadimage ']
# toolbar_location: "external"
# resizing: true
# path: true
# resize_horizontal: false
# resize_vertical: true
menubar: false
resizing_use_cookie: true
uploadimage_default_img_class: mce-upload-image
extended_valid_elements:
  - "iframe[src|title|width|height|allowfullscreen|frameborder]"
  - "embed[width|height|name|flashvars|src|bgcolor|align|play|loop|quality|allowscriptaccess|type|pluginspage]"
style_formats:
  - title: R-to-L
    block: div
    classes: rtl
  - title: Video
    block: div
    classes: video-player
content_css: "https://s3.amazonaws.com/ocill-bucket/public/content.css"
plugins:
  - textcolor
  - uploadimage
  - link
  - code
media_strict: false
mode: textareas